# Generated by Django 5.0.3 on 2024-04-04 04:54

import django.core.validators
import django.db.models.deletion
import surat_masuk.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DbDerajatSurat',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('dejarat_surat', models.CharField(max_length=30)),
            ],
            options={
                'db_table': 'DbDerajatSurat',
            },
        ),
        migrations.CreateModel(
            name='DbJenisSurat',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('jenis_surat', models.CharField(max_length=30)),
                ('inisial_nama', models.CharField(max_length=30)),
            ],
            options={
                'db_table': 'JenisSurat',
            },
        ),
        migrations.CreateModel(
            name='DbKlasifikasi',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('klasifikasi', models.CharField(max_length=30)),
            ],
            options={
                'db_table': 'Klasifikasi',
            },
        ),
        migrations.CreateModel(
            name='DbSurat',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('username', models.CharField(max_length=30)),
                ('jenis_surat', models.CharField(blank=True, max_length=30, null=True)),
                ('klasifikasi', models.CharField(blank=True, max_length=30, null=True)),
                ('tgl_agenda', models.DateField()),
                ('id_jenis_surat', models.CharField(max_length=1)),
                ('no_agenda', models.CharField(max_length=30, unique=True)),
                ('tgl_surat', models.DateField(blank=True, null=True)),
                ('no_surat', models.CharField(max_length=30)),
                ('surat_dari', models.CharField(max_length=110)),
                ('derajat_surat', models.CharField(blank=True, max_length=30, null=True)),
                ('perihal', models.CharField(max_length=200)),
                ('upload_file', models.FileField(upload_to=surat_masuk.models.save_file_surat, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf'])])),
            ],
            options={
                'db_table': 'DbSurat',
            },
        ),
        migrations.CreateModel(
            name='TempNoAgenda',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=30)),
                ('no_agenda', models.CharField(max_length=30)),
                ('jenis_surat', models.CharField(max_length=30)),
                ('tgl_agenda', models.DateField()),
            ],
            options={
                'db_table': 'TempNoAgenda',
            },
        ),
        migrations.CreateModel(
            name='DisposisiDb',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('username', models.CharField(max_length=30)),
                ('disposisi', models.CharField(max_length=30)),
                ('tgl_disposisi', models.DateField()),
                ('tgl_disposisi_kembali', models.DateField(blank=True, null=True)),
                ('no_agenda', models.CharField(max_length=30, null=True)),
                ('catatan', models.CharField(max_length=200)),
                ('upload_file_disposisi', models.FileField(blank=True, null=True, upload_to=surat_masuk.models.save_file_disposisi, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf'])])),
                ('no_surat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='surat_masuk.dbsurat')),
            ],
            options={
                'db_table': 'DisposisiDb',
            },
        ),
    ]
